<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="html+css.css">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <title>Document</title>

    </style>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
<div class="navbar-brend col-xs-6 col-sm-8 col-md-8 col-lg-9">

            <div id="hamburger-menu" class="col-xs-6 col-sm-4 col-md-4 col-lg-3">
                <input id="menu__toggle" type="checkbox" />
                <label class="menu__btn" for="menu__toggle">
                  <span></span>
                </label>
                <ul class="menu__box">
                  <li><a class="menu__item" href="#">Главная</a></li>
                  <li><a class="menu__item" href="#">Проекты</a></li>
                  <li><a class="menu__item" href="#">Команда</a></li>
                  <li><a class="menu__item" href="#">Блог</a></li>
                  <li><a class="menu__item" href="#">Контакты</a></li>
                </ul>
              </div>
        </div>

</div>
</nav>
    <div>
        <div  id="main"></div>
      <div class="img__text">
        <h1 style="font-size: 90px;">Robots Are <br> The Future</h1>
        <h3 style="font-size: 30px;">Lorem ipsum dolor sit amet, consectetur adipiscing <br> elit nullam nunc justo sagittis suscipit ultrices.</h3>
      </div>
    </div>

  <div></div>
  <div class="row__top">
    <div class="row">
      <div class="column">
        <main style="font-size:25px;">TECHNOLOGY NEWS </main>
        <h1 style="font-size: 60px;">Human-robot</h1>
        <p style="font-size: 18px;">In human-robot collaboration, the robot assists the human <br>operator. This means: The machine does not replace the <br>human, but complements his capabilities and relieves him <br> of arduous tasks. These can include overhead work, for <br>example, or the lifting of heavy loads. Autonomous, <br>collaborative robots are also used to supply production <br> workstations</p>
      </div>
    </div>
    <div class="row">
      <div class="jpeg"></div>
    </div>
  </div>





    
    
    
<div class="list">
  <div class="e__lista">
    <h2 style="margin-top: -20px;">FUTURE OF WORK
    </h2>
    <h3 style="font-size: 20px;">While much of the discourse around  AI and automation <br>  has been concerned with the looming threat to the workforce...</h3>
    <div class="d">
      <div class="cvadrat"></div>
      <div class="cvadrat"></div>
      <div class="cvadrat"></div>
    </div>
  </div>
  <div class="e__lista">
    <div class="dm">
      <div class="cvadrad"></div>
      <div class="cvadrad"></div>
      <div class="cvadrad"></div>
    </div>
  </div>
</div>    

<div>
  <div class="ll">
    <div class="m" ></div>
    <div class="m"></div>
  </div>
  <div class="mk">
    <div class="nn"></div>
    <div class="nn"></div>
  </div>
</div>
    
    <div class="da">
      <h1>
        LEARN
      </h1>
    </div>








    <div class="glava">
      <div class="link"><h2>Robotization</h2>
      <p style="font-size: 25px;">When the first industrial revolution <br> hit ipsum dolor sit amet <br>, consectetur adipiscing elit nullam <br> nunc justo sagittis suscipit ultrices.</p>
      </div>
      <div class="link">
        <h2>Robotization</h2>
      <p style="font-size: 25px;">When the first industrial revolution <br> hit ipsum dolor sit amet, <br> consectetur adipiscing elit nullam <br> nunc justo sagittis suscipit ultrices.</p>
      </div>
      <div class="link">
        <h2>Robotization</h2>
      <p style="font-size: 25px;">When the first industrial revolution <br> hit ipsum dolor sit amet, <br> consectetur adipiscing elit nullam <br> nunc justo sagittis suscipit ultrices.</p>
      </div>
    </div>






    <div>
<div class="hh">
  <h1 style="color:coral;">Technology Trends</h1>
  <main>Maximum flexibility in production. Relief of employees by performing ergonomically unfavorable work steps that could not previously be automated</main>
</div>
<div class="gg">
  <div class="photo"></div>
  <div class="photo"></div>
  <div class="photo"></div>
</div>
    </div>





<footer>
<blockquote style="font-size: 30px;">We need to know what the resources of  the moon are. We have great evidence now because of <br> different kinds of radar and spectroscopic analysis that people have been able to do. But we <br> really do need to go visit there, and we can do that with a robot craft without any problem. <br>

  <h2 style="margin-left: 80vw;">- Jeff Bezos -</h2></blockquote>
</footer>




<div class="kk">
  <div class="ss">


    <div class="main"></div>
  </div>
  <div class="ss">
 
      <h1>
        Artificial Intelligence Robots And The Future Of Work</h1>
        <main>The number of robots in the world today is approaching <br> 1,000,000, with almost half that number in Japan and <br>just 15% in the US. A couple of decades ago, 90% of robots <br> were used in car manufacturing, typically on assembly <br> lines doing a variety of repetitive tasks. Today only 50% are in automobile plants, with the other half spread out among other factories, and many other industries.</main>
  </div>
</div>




<div class="ks">
  <div class="bb">


    <div class="mail"></div>
  </div>
  <div class="bb">
 
      <h1>
        Artificial Intelligence Robots And The Future Of Work</h1>
        <main>The number of robots in the world today is approaching <br> 1,000,000, with almost half that number in Japan and <br>just 15% in the US. A couple of decades ago, 90% of robots <br> were used in car manufacturing, typically on assembly <br> lines doing a variety of repetitive tasks. Today only 50% are in automobile plants, with the other half spread out among other factories, and many other industries.</main>
  </div>
</div>
  </body>
</html>
